// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passman.proto

package passman

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeec5599de9f1e6a, []int{0}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetReq) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type Credentials struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeec5599de9f1e6a, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ServiceCredentials struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceCredentials) Reset()         { *m = ServiceCredentials{} }
func (m *ServiceCredentials) String() string { return proto.CompactTextString(m) }
func (*ServiceCredentials) ProtoMessage()    {}
func (*ServiceCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeec5599de9f1e6a, []int{2}
}

func (m *ServiceCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceCredentials.Unmarshal(m, b)
}
func (m *ServiceCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceCredentials.Marshal(b, m, deterministic)
}
func (m *ServiceCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceCredentials.Merge(m, src)
}
func (m *ServiceCredentials) XXX_Size() int {
	return xxx_messageInfo_ServiceCredentials.Size(m)
}
func (m *ServiceCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceCredentials proto.InternalMessageInfo

func (m *ServiceCredentials) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceCredentials) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ServiceCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*GetReq)(nil), "passman.GetReq")
	proto.RegisterType((*Credentials)(nil), "passman.Credentials")
	proto.RegisterType((*ServiceCredentials)(nil), "passman.ServiceCredentials")
}

func init() {
	proto.RegisterFile("passman.proto", fileDescriptor_eeec5599de9f1e6a)
}

var fileDescriptor_eeec5599de9f1e6a = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0x2c, 0x2e,
	0xce, 0x4d, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x9c, 0xb8,
	0xd8, 0xdc, 0x53, 0x4b, 0x82, 0x52, 0x0b, 0x85, 0xc4, 0xb8, 0xd8, 0x42, 0x8b, 0x53, 0x8b, 0x3c,
	0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xa0, 0x3c, 0x21, 0x05, 0x2e, 0xee, 0xe0, 0xd4,
	0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x64, 0x21, 0x25, 0x7b, 0x2e, 0x6e, 0xe7, 0xa2, 0xd4, 0x94, 0xd4, 0xbc, 0x92, 0xcc, 0xc4, 0x9c,
	0x62, 0x21, 0x11, 0x2e, 0x56, 0x9f, 0xfc, 0xf4, 0xcc, 0x3c, 0xb0, 0x39, 0x9c, 0x41, 0x10, 0x8e,
	0x90, 0x14, 0x17, 0x47, 0x40, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x0a, 0xd4, 0x0c, 0x38, 0x5f,
	0x29, 0x83, 0x4b, 0x08, 0x6a, 0x1e, 0xb2, 0x39, 0x68, 0x16, 0x33, 0x62, 0x58, 0x8c, 0xb0, 0x89,
	0x09, 0x97, 0x4d, 0xcc, 0xa8, 0x36, 0x19, 0x05, 0x71, 0xf1, 0x05, 0x40, 0x7c, 0x0e, 0x35, 0x47,
	0xc8, 0x81, 0x8b, 0xcf, 0x3d, 0xb5, 0x04, 0xd9, 0x5e, 0x7e, 0x3d, 0x58, 0x58, 0x41, 0x42, 0x46,
	0x4a, 0x1a, 0x2e, 0x80, 0xe9, 0x4a, 0x25, 0x06, 0x27, 0x9e, 0x28, 0x2e, 0x3d, 0x7d, 0x6b, 0xa8,
	0x92, 0x24, 0x36, 0x70, 0x00, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x14, 0x55, 0xfb,
	0x71, 0x01, 0x00, 0x00,
}
